In [134]:
import pandas as pd
import numpy as np

In [135]:
football_file = pd.read_csv('appearances.csv')

np.random.seed(0)

In [136]:
football_file.head()

,gameID,playerID,goals,ownGoals,shots,xGoals,xGoalsChain,xGoalsBuildup,assists,keyPasses,xAssists,position,positionOrder,yellowCard,redCard,time,substituteIn,substituteOut,leagueID
0,81,560,0,0,0,0.0,0.000000,0.000000,0,0,0.000000,GK,1,0,0,90,0,0,1
1,81,557,0,0,0,0.0,0.106513,0.106513,0,1,0.106513,DR,2,0,0,82,222605,0,1
2,81,548,0,0,0,0.0,0.127738,0.127738,0,0,0.000000,DC,3,0,0,90,0,0,1
3,81,628,0,0,0,0.0,0.106513,0.106513,0,0,0.000000,DC,3,0,0,90,0,0,1
4,81,1006,0,0,0,0.0,0.021225,0.021225,0,0,0.000000,DL,4,0,0,90,0,0,1

In [137]:
football_file.tail()

,gameID,playerID,goals,ownGoals,shots,xGoals,xGoalsChain,xGoalsBuildup,assists,keyPasses,xAssists,position,positionOrder,yellowCard,redCard,time,substituteIn,substituteOut,leagueID
356508,16135,3509,0,0,1,0.028713,0.058495,0.058495,0,0,0.000000,MC,9,0,0,90,0,0,5
356509,16135,4882,0,0,1,0.013482,0.058495,0.045374,0,2,0.058495,MC,9,0,0,90,0,0,5
356510,16135,5786,0,0,0,0.000000,0.045374,0.045374,0,0,0.000000,FW,15,0,0,90,0,0,5
356511,16135,8997,0,0,0,0.000000,0.000000,0.000000,0,0,0.000000,FW,15,0,0,78,474075,0,5
356512,16135,5762,0,0,0,0.000000,0.000000,0.000000,0,0,0.000000,Sub,17,0,0,12,0,474074,5

In [138]:
football_file.shape

(356513, 19)

In [139]:
list[football_file.columns]

list[Index(['gameID', 'playerID', 'goals', 'ownGoals', 'shots', 'xGoals',
       'xGoalsChain', 'xGoalsBuildup', 'assists', 'keyPasses', 'xAssists',
       'position', 'positionOrder', 'yellowCard', 'redCard', 'time',
       'substituteIn', 'substituteOut', 'leagueID'],
      dtype='object')]

In [140]:
football_file.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 356513 entries, 0 to 356512
Data columns (total 19 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   gameID         356513 non-null  int64
 1   playerID       356513 non-null  int64
 2   goals          356513 non-null  int64
 3   ownGoals       356513 non-null  int64
 4   shots          356513 non-null  int64
 5   xGoals         356513 non-null  float64
 6   xGoalsChain    356513 non-null  float64
 7   xGoalsBuildup  356513 non-null  float64
 8   assists        356513 non-null  int64
 9   keyPasses      356513 non-null  int64
 10  xAssists       356513 non-null  float64
 11  position       356513 non-null  object
 12  positionOrder  356513 non-null  int64
 13  yellowCard     356513 non-null  int64
 14  redCard        356513 non-null  int64
 15  time           356513 non-null  int64
 16  substituteIn   356513 non-null  int64
 17  substituteOut  356513 non-null  int64
 18  leagueID       356513 non-null  int64
dtypes: float64(4), int64(14), object(1)
memory usage: 51.7+ MB

In [141]:
football_file.describe()

,gameID,playerID,goals,ownGoals,shots,xGoals,xGoalsChain,xGoalsBuildup,assists,keyPasses,xAssists,positionOrder,yellowCard,redCard,time,substituteIn,substituteOut,leagueID
count,356513.000000,356513.000000,356513.000000,356513.000000,356513.000000,356513.000000,356513.000000,356513.000000,356513.000000,356513.000000,356513.000000,356513.000000,356513.000000,356513.000000,356513.000000,356513.000000,356513.000000,356513.000000
mean,7974.122739,2888.112128,0.094574,0.002844,0.886447,0.096771,0.254942,0.149973,0.066152,0.656666,0.067767,9.356655,0.141445,0.007240,70.260714,51970.072631,51968.950341,2.991103
std,4790.920538,2365.073266,0.329592,0.053361,1.270494,0.224492,0.352763,0.249580,0.265908,1.032937,0.160254,5.831530,0.348481,0.084777,29.822916,120148.262277,120146.437953,1.432223
min,81.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,1.000000
25%,3856.000000,952.000000,0.000000,0.000000,0.000000,0.000000,0.018633,0.000000,0.000000,0.000000,0.000000,3.000000,0.000000,0.000000,58.000000,0.000000,0.000000,2.000000
50%,8074.000000,2210.000000,0.000000,0.000000,0.000000,0.000000,0.109935,0.046066,0.000000,0.000000,0.000000,9.000000,0.000000,0.000000,90.000000,0.000000,0.000000,3.000000
75%,12154.000000,4345.000000,0.000000,0.000000,1.000000,0.076644,0.370235,0.166904,0.000000,1.000000,0.056451,15.000000,0.000000,0.000000,90.000000,0.000000,0.000000,4.000000
max,16135.000000,9568.000000,5.000000,2.000000,14.000000,3.933408,5.052705,3.558237,4.000000,12.000000,3.078499,17.000000,1.000000,1.000000,90.000000,474107.000000,474101.000000,5.000000

In [142]:
football_file.describe(include='O')

       position
count    356513
unique       17
top         Sub
freq      77563

In [143]:
football_file['gameID'].value_counts()

gameID
15527    32
15551    32
16118    32
16116    32
15550    32
         ..
5949     23
5959     23
11858    23
5999     22
5825     22
Name: count, Length: 12680, dtype: int64

In [144]:
football_file['goals'].value_counts()

goals
0    326415
1     26906
2      2813
3       337
4        36
5         6
Name: count, dtype: int64

In [145]:
football_file[['goals']]

        goals
0           0
1           0
2           0
3           0
4           0
...       ...
356508      0
356509      0
356510      0
356511      0
356512      0

[356513 rows x 1 columns]

In [146]:
football_file[['goals']].mean()

goals    0.094574
dtype: float64

In [147]:
football_file['leagueID'].value_counts()

leagueID
2    75538
4    75382
1    73305
5    71797
3    60491
Name: count, dtype: int64

In [148]:
football_file[['gameID']]

        gameID
0           81
1           81
2           81
3           81
4           81
...        ...
356508   16135
356509   16135
356510   16135
356511   16135
356512   16135

[356513 rows x 1 columns]

In [149]:
football_file['leagueID'].unique()

array([1, 2, 3, 4, 5])

In [150]:
football_file.isnull().sum()

gameID           0
playerID         0
goals            0
ownGoals         0
shots            0
xGoals           0
xGoalsChain      0
xGoalsBuildup    0
assists          0
keyPasses        0
xAssists         0
position         0
positionOrder    0
yellowCard       0
redCard          0
time             0
substituteIn     0
substituteOut    0
leagueID         0
dtype: int64

In [151]:
football_file.duplicated().sum()

np.int64(0)

In [152]:
football_file['goals'].agg(['max', 'min', 'mean'])

max     5.000000
min     0.000000
mean    0.094574
Name: goals, dtype: float64

In [153]:
football_file[football_file['goals'] == 5.000000]

,gameID,playerID,goals,ownGoals,shots,xGoals,xGoalsChain,xGoalsBuildup,assists,keyPasses,xAssists,position,positionOrder,yellowCard,redCard,time,substituteIn,substituteOut,leagueID
2025,154,619,5,0,8,1.904508,1.544558,0.120013,0,0,0.000000,FW,15,0,0,69,64829,0,1
27329,1066,227,5,0,9,3.197079,3.284968,0.000000,0,1,0.087889,Sub,17,0,0,44,0,85999,3
37161,1420,2371,5,0,7,3.226308,3.414285,0.000000,1,3,0.931255,AML,13,0,0,90,0,0,4
132014,5510,2371,5,0,13,3.503829,3.372064,0.117822,0,2,0.178014,FWL,16,0,0,90,0,0,4
149511,6142,4753,5,0,8,2.572862,2.667935,0.449377,0,0,0.000000,AMC,12,0,0,90,0,0,5
235908,10403,6228,5,0,6,0.796744,0.796744,0.000000,0,0,0.000000,FW,15,0,0,88,282666,0,3

In [154]:
football_file['redCard'].agg(['max', 'min', 'mean'])

max     1.00000
min     0.00000
mean    0.00724
Name: redCard, dtype: float64

In [155]:
football_file[football_file['redCard'] == 0.00000]

,gameID,playerID,goals,ownGoals,shots,xGoals,xGoalsChain,xGoalsBuildup,assists,keyPasses,xAssists,position,positionOrder,yellowCard,redCard,time,substituteIn,substituteOut,leagueID
0,81,560,0,0,0,0.000000,0.000000,0.000000,0,0,0.000000,GK,1,0,0,90,0,0,1
1,81,557,0,0,0,0.000000,0.106513,0.106513,0,1,0.106513,DR,2,0,0,82,222605,0,1
2,81,548,0,0,0,0.000000,0.127738,0.127738,0,0,0.000000,DC,3,0,0,90,0,0,1
3,81,628,0,0,0,0.000000,0.106513,0.106513,0,0,0.000000,DC,3,0,0,90,0,0,1
4,81,1006,0,0,0,0.000000,0.021225,0.021225,0,0,0.000000,DL,4,0,0,90,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
356508,16135,3509,0,0,1,0.028713,0.058495,0.058495,0,0,0.000000,MC,9,0,0,90,0,0,5
356509,16135,4882,0,0,1,0.013482,0.058495,0.045374,0,2,0.058495,MC,9,0,0,90,0,0,5
356510,16135,5786,0,0,0,0.000000,0.045374,0.045374,0,0,0.000000,FW,15,0,0,90,0,0,5
356511,16135,8997,0,0,0,0.000000,0.000000,0.000000,0,0,0.000000,FW,15,0,0,78,474075,0,5
356512,16135,5762,0,0,0,0.000000,0.000000,0.000000,0,0,0.000000,Sub,17,0,0,12,0,474074,5

In [156]:
football_file.loc[100:110, 'gameID']

100    84
101    84
102    84
103    84
104    84
105    84
106    84
107    84
108    84
109    84
110    84
Name: gameID, dtype: int64

In [157]:
football_file.iloc[80:90, 13]

80    1
81    0
82    0
83    0
84    0
85    0
86    0
87    0
88    1
89    0
Name: yellowCard, dtype: int64

In [158]:
football_file.set_index('gameID', inplace=True)
football_file

,playerID,goals,ownGoals,shots,xGoals,xGoalsChain,xGoalsBuildup,assists,keyPasses,xAssists,position,positionOrder,yellowCard,redCard,time,substituteIn,substituteOut,leagueID
gameID,,,,,,,,,,,,,,,,,,
81,560,0,0,0,0.000000,0.000000,0.000000,0,0,0.000000,GK,1,0,0,90,0,0,1
81,557,0,0,0,0.000000,0.106513,0.106513,0,1,0.106513,DR,2,0,0,82,222605,0,1
81,548,0,0,0,0.000000,0.127738,0.127738,0,0,0.000000,DC,3,0,0,90,0,0,1
81,628,0,0,0,0.000000,0.106513,0.106513,0,0,0.000000,DC,3,0,0,90,0,0,1
81,1006,0,0,0,0.000000,0.021225,0.021225,0,0,0.000000,DL,4,0,0,90,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16135,3509,0,0,1,0.028713,0.058495,0.058495,0,0,0.000000,MC,9,0,0,90,0,0,5
16135,4882,0,0,1,0.013482,0.058495,0.045374,0,2,0.058495,MC,9,0,0,90,0,0,5
16135,5786,0,0,0,0.000000,0.045374,0.045374,0,0,0.000000,FW,15,0,0,90,0,0,5
16135,8997,0,0,0,0.000000,0.000000,0.000000,0,0,0.000000,FW,15,0,0,78,474075,0,5
16135,5762,0,0,0,0.000000,0.000000,0.000000,0,0,0.000000,Sub,17,0,0,12,0,474074,5

In [159]:
football_file.reset_index('gameID', inplace=True)
football_file

,gameID,playerID,goals,ownGoals,shots,xGoals,xGoalsChain,xGoalsBuildup,assists,keyPasses,xAssists,position,positionOrder,yellowCard,redCard,time,substituteIn,substituteOut,leagueID
0,81,560,0,0,0,0.000000,0.000000,0.000000,0,0,0.000000,GK,1,0,0,90,0,0,1
1,81,557,0,0,0,0.000000,0.106513,0.106513,0,1,0.106513,DR,2,0,0,82,222605,0,1
2,81,548,0,0,0,0.000000,0.127738,0.127738,0,0,0.000000,DC,3,0,0,90,0,0,1
3,81,628,0,0,0,0.000000,0.106513,0.106513,0,0,0.000000,DC,3,0,0,90,0,0,1
4,81,1006,0,0,0,0.000000,0.021225,0.021225,0,0,0.000000,DL,4,0,0,90,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
356508,16135,3509,0,0,1,0.028713,0.058495,0.058495,0,0,0.000000,MC,9,0,0,90,0,0,5
356509,16135,4882,0,0,1,0.013482,0.058495,0.045374,0,2,0.058495,MC,9,0,0,90,0,0,5
356510,16135,5786,0,0,0,0.000000,0.045374,0.045374,0,0,0.000000,FW,15,0,0,90,0,0,5
356511,16135,8997,0,0,0,0.000000,0.000000,0.000000,0,0,0.000000,FW,15,0,0,78,474075,0,5
356512,16135,5762,0,0,0,0.000000,0.000000,0.000000,0,0,0.000000,Sub,17,0,0,12,0,474074,5

In [160]:
football_file.groupby('gameID')['goals'].mean().reset_index()

       gameID     goals
0          81  0.000000
1          82  0.035714
2          83  0.142857
3          84  0.222222
4          85  0.142857
...       ...       ...
12675   16131  0.096774
12676   16132  0.096774
12677   16133  0.062500
12678   16134  0.033333
12679   16135  0.083333

[12680 rows x 2 columns]

In [162]:
gameID = football_file.pivot_table(index='gameID', values='goals', aggfunc=(['max', 'min', 'mean']))
gameID

         max   min      mean
       goals goals     goals
gameID
81         0     0  0.000000
82         1     0  0.035714
83         1     0  0.142857
84         2     0  0.222222
85         1     0  0.142857
...      ...   ...       ...
16131      1     0  0.096774
16132      1     0  0.096774
16133      1     0  0.062500
16134      1     0  0.033333
16135      1     0  0.083333

[12680 rows x 3 columns]

In [165]:
leagueID = football_file.pivot_table(index='leagueID', values='goals', aggfunc=['max', 'min', 'mean'])
leagueID

           max   min      mean
         goals goals     goals
leagueID
1            5     0  0.095137
2            4     0  0.096044
3            5     0  0.101883
4            5     0  0.091335
5            5     0  0.089697